# The URL the site will be built for
base_url = "https://sysrex.com"

title = "sysrex"
description = "This is mostly about the things that I am learning and don't want to forget just yet!"

default_language = "en"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

theme = "nivis"

generate_feeds = true
feed_filenames = ["atom.xml"]

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

taxonomies = [{ name = "tags", feed = true, paginate_by = 5 }]

[search]
index_format = "fuse_json"
include_title = true
include_description = true
include_content = true

[markdown]
render_emoji = true
github_alerts = true
bottom_footnotes = true

[markdown.highlighting]
style = "class"
light_theme = "one-light"
dark_theme = "one-dark-pro"

[extra]
avatar = ""

home_layout = "focus"
taxonomy_mode = "tags"
content_lang = ""
motto_mode = "hide"

social_links = [
    { name = "github", url = "https://github.com/sysrex" },
    { name = "twitter", url = "https://twitter.com/sysrex" },
    { name = "rss", url = "https://sysrex.com/atom.xml" },
]

[extra.footer]
copyright_holder = ""
copyright_since = 0

[extra.sections]
posts = true
about = false
archive = true
tags = true
links = false
