# The URL the site will be built for
base_url = "https://sysrex.com"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Add papermode theme
theme = "papermod"

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true


taxonomies = [{ name = "tags", feed = true }]

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

[extra]
# Put all your custom variables here

[extra.papermod]
title = "AiSlop"
default_theme = "auto"
theme = "light"
language_direction = "auto"
keywords = ["keyword1", "keyword2", "keyword3"]
show_theme_toggle = true
show_scroll_to_top = true
show_code_copy_buttons = true
show_reading_time = true
show_word_count = false
show_post_nav_links = true
show_post_meta = true
default_toc_open = false
show_post_edit_button = false
show_archive_year_count = true
show_archive_month_count = true
edit_post_url = "https://github.com/sysrex/sysrex-website/tree/main"
#copyright = ""
date_format = "%Y-%m-%d"
navigation = [
    { url = "$BASE_URL/archive", title = "Archive" },
    { url = "$BASE_URL/tags", title = "Tags" },
    { url = "$BASE_URL/search", title = "Search" },
    { url = "https://sysrex.com/", title = "sysrex", is_external = true },
]

home_title = "My ramblings"
home_content = "Welcome to my ramblings, this mostly about the things that I am learning and don't want to forget just yet! "
social_icons = [
    { url = "https://github.com/sysrex", title = "GitHub", icon = "github" },
    { url = "https://twitter.com/sysrex", title = "Twitter", icon = "twitter" },
    { url = "$BASE_URL/atom.xml", title = "RSS", icon = "rss" },
]
